import nodemailer from "nodemailer";
import type { Connector, ConnectorFactory } from "@agent-hub/core";
import type { IntegrationKind, TenantContext } from "@agent-hub/core";

// SMTP-based Gmail connector.
//
// Why SMTP and not the Gmail API:
//   - Avoids full OAuth2 setup (Google Cloud Console, client id/secret,
//     consent screen, redirect URIs, token refresh, etc.)
//   - Works with a Gmail App Password (16 chars, generated by the user in
//     their Google account when 2FA is on). Pasted once in the dashboard
//     settings UI and stored in integrations.credentials.
//
// Tradeoff: if the user rotates their password or revokes the app password,
// they must paste a new one. But setup is literally: enable 2FA → generate
// app password → paste in form.
//
// Credentials schema (stored in integrations.credentials jsonb):
//   {
//     from: "sales@weknowit.se",   // sender email (also SMTP username)
//     password: "xxxx xxxx xxxx xxxx"  // 16-char Google App Password
//   }

export interface EmailMessage {
  to: string;
  cc?: string[];
  subject: string;
  body_html: string;
  body_text?: string;
  reply_to?: string;
}

export interface EmailConnector extends Connector {
  sendEmail(msg: EmailMessage): Promise<{ message_id: string }>;
  createDraft(msg: EmailMessage): Promise<{ draft_id: string }>;
}

interface GmailSmtpCreds {
  from: string;
  password: string;
}

class GmailSmtpConnector implements EmailConnector {
  readonly kind: IntegrationKind = "gmail";
  private readonly transporter: nodemailer.Transporter;

  constructor(
    readonly tenant: TenantContext,
    private readonly creds: GmailSmtpCreds,
  ) {
    if (!creds.from || !creds.password) {
      throw new Error(
        "GmailSmtpConnector: credentials must include { from, password } (Gmail App Password).",
      );
    }
    this.transporter = nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 587,
      secure: false, // STARTTLS
      auth: {
        user: creds.from,
        pass: creds.password,
      },
    });
  }

  async healthcheck() {
    try {
      await this.transporter.verify();
      return { ok: true };
    } catch (e) {
      return { ok: false, message: (e as Error).message };
    }
  }

  async sendEmail(msg: EmailMessage) {
    const info = await this.transporter.sendMail({
      from: this.creds.from,
      to: msg.to,
      cc: msg.cc,
      replyTo: msg.reply_to,
      subject: msg.subject,
      html: msg.body_html,
      text: msg.body_text,
    });
    return { message_id: info.messageId };
  }

  /**
   * "Draft" mode — we don't hit Gmail drafts via SMTP, so we just verify the
   * transport is live. The Sales Agent's flow is: draft_outreach_approval →
   * approveAction() → sendEmail(). This method is kept for interface parity
   * and only used by agents/tools that explicitly want a pre-send verification.
   */
  async createDraft(_msg: EmailMessage) {
    await this.transporter.verify();
    return { draft_id: `smtp-verified-${Date.now()}` };
  }
}

export const gmailFactory: ConnectorFactory<EmailConnector> = {
  kind: "gmail",
  async create({ tenant, credentials }) {
    return new GmailSmtpConnector(tenant, credentials as unknown as GmailSmtpCreds);
  },
};